# Format: RequestClass=ResponseClass:field1=field1Response,field2=field2Response

PersonCreateRequest=PersonResponse:gender=gender,birthdate=birthdate,names[0].givenName=display,names[0].familyName=display,addresses[0].address1=preferredAddress.display
PersonAddressCreateRequest=PersonAddressResponse:address1=address1,cityVillage=cityVillage,stateProvince=stateProvince,postalCode=postalCode
PersonUpdateRequest=PersonResponse:gender=gender,birthdate=birthdate

# PatientPatientIdentifierType
PatientIdentifierTypeCreateRequest=PatientIdentifierTypeResponse:name=name,description=description,format=format,formatDescription=formatDescription,required=required,validator=validator,locationBehavior=locationBehavior,uniquenessBehavior=uniquenessBehavior

# Location
LocationCreateRequest=LocationResponse:name=name,description=description,address1=address1,cityVillage=cityVillage,stateProvince=stateProvince,country=country,postalCode=postalCode,countyDistrict=countyDistrict,tags=tags,childLocations=childLocations,attributes=attributes

# Patient
PatientCreateNewRequest=PatientResponse:person.gender=person.gender,person.dead=person.dead,person.birthdateEstimated=person.birthdateEstimated,person.deathDate=person.deathDate,person.causeOfDeath=person.causeOfDeath,person.birthdate=person.birthdate
PatientCreateFromExistingPersonRequest=PatientResponse:person=uuid
PatientIdentifierCreateRequest=patientIdentifierResponse:identifier=identifier,identifierType=identifierType.uuid,location=location.uuid,preferred=preferred
PatientIdentifierUpdateRequest=patientIdentifierResponse:identifier=identifier

#Visit
VisitResponse=PatientResponse:location.uuid=location,visitType.uuid=visitType,patient.uuid=patient