### Логин (setup)
GET http://localhost/openmrs/ws/rest/v1/session
Authorization: Basic YWRtaW46QWRtaW4xMjM=
Accept: application/json

### Запросить все роли
GET http://localhost/openmrs/ws/rest/v1/role?v=full
Authorization: Basic YWRtaW46QWRtaW4xMjM=
Accept: application/json

### Посмотреть какие методы поддерживаются
OPTIONS http://localhost/openmrs/ws/rest/v1/person/1da80315-96ec-47de-aa32-61a864002b1f
Authorization: Basic YWRtaW46QWRtaW4xMjM=

### Список всех атрибутов Person какие есть в системе
GET http://localhost/openmrs/ws/rest/v1/personattributetype?v=full
Content-Type: application/json
Authorization: Basic YWRtaW46QWRtaW4xMjM=
Accept: application/json

### 1.  Создание минимального Person (только имена + gender) -> 201
POST http://localhost/openmrs/ws/rest/v1/person
Content-Type: application/json
Authorization: Basic YWRtaW46QWRtaW4xMjM=
Accept: application/json

{
  "names": [
    {
      "givenName": "Test",
      "familyName": "Person",
      "preferred": true
    }
  ],
  "gender": "O"
}

### 2.  Поиск Person по имени -> 200
GET http://localhost/openmrs/ws/rest/v1/person?q=Ivan
Content-Type: application/json
Authorization: Basic YWRtaW46QWRtaW4xMjM=
Accept: application/json


### 3.  Поиск Person по имени если такого нет -> 200 //{"results":[]}

GET http://localhost/openmrs/ws/rest/v1/person?q=kot
Content-Type: application/json
Authorization: Basic YWRtaW46QWRtaW4xMjM=
Accept: application/json

### 4.  Поиск Person по UUID -> 200
GET http://localhost/openmrs/ws/rest/v1/person/4440c392-99ad-4e55-8d63-725df4992a84
Content-Type: application/json
Authorization: Basic YWRtaW46QWRtaW4xMjM=
Accept: application/json

### 5.  Поиск Person по UUID если такого нет -> 404
GET http://localhost/openmrs/ws/rest/v1/person/4ef1f0f9-fee6-414b-910d-28e17df345c2
Content-Type: application/json
Authorization: Basic YWRtaW46QWRtaW4xMjM=
Accept: application/json

### 6.  Создание Person с birthdate, estimated age, addresses, attributes -> 201
POST http://localhost/openmrs/ws/rest/v1/person
Content-Type: application/json
Authorization: Basic YWRtaW46QWRtaW4xMjM=
Accept: application/json

{
  "names": [{"givenName": "Ivan", "middleName": "Petrovich", "familyName": "Ivanov", "preferred": true}],
  "gender": "M",
  "birthdate": "1985-03-15",
  "birthdateEstimated": false,
  "dead": false,
  "addresses": [{
    "address1": "Hauptstr. 12",
    "cityVillage": "München",
    "stateProvince": "Bayern",
    "country": "Germany",
    "postalCode": "80331",
    "preferred": true
  }],
  "attributes": [{
    "attributeType": "14d4f066-15f5-102d-96e4-000c29c2a5d7",
    "value": "+49123456789"
  }]
}

### 7.  Создание Person: создание с одинаковым именем -> 201
POST http://localhost/openmrs/ws/rest/v1/person
Content-Type: application/json
Authorization: Basic YWRtaW46QWRtaW4xMjM=
Accept: application/json

{
  "names": [
    {
      "givenName": "Test",
      "familyName": "Person",
      "preferred": true
    }
  ],
  "gender": "O"
}

### 8.  Создание Person Negative: создание без gender -> 400 //{"error":{"message":"[Some required properties are missing: gender]"
POST http://localhost/openmrs/ws/rest/v1/person
Content-Type: application/json
Authorization: Basic YWRtaW46QWRtaW4xMjM=
Accept: application/json

{
  "names": [
    {
      "givenName": "Test",
      "familyName": "Person"
    }
  ]
}

### 9.  Создание Person Negative: создание без хотя бы одного имени -> 400 //{"error":{"message":"[names on class org.openmrs.Person]"
POST http://localhost/openmrs/ws/rest/v1/person
Content-Type: application/json
Authorization: Basic YWRtaW46QWRtaW4xMjM=
Accept: application/json

{
  "names": [],
  "gender": "O"
}

### 10.  Создание Person Negative: некорректный gender (не M/F/O) -> 400  //приходит 200
POST http://localhost/openmrs/ws/rest/v1/person
Content-Type: application/json
Authorization: Basic YWRtaW46QWRtaW4xMjM=
Accept: application/json

{
  "names": [
    {
      "givenName": "Test",
      "familyName": "Person",
      "preferred": true
    }
  ],
  "gender": "7"
}

### 11.  Создание Person Negative: birthdate в будущем -> 400 //{"error":{"message":"Invalid Submission","code":"webservices.rest.error.invalid.submission","globalErrors":[],"fieldErrors":{"birthdate":[{"code":"error.date.future","message":"Cannot be a date in the future"}]}}}
POST http://localhost/openmrs/ws/rest/v1/person
Content-Type: application/json
Authorization: Basic YWRtaW46QWRtaW4xMjM=
Accept: application/json

{
  "names": [{"givenName": "Ivan", "middleName": "Petrovich", "familyName": "Ivanov", "preferred": true}],
  "gender": "M",
  "birthdate": "2034-03-15",
  "birthdateEstimated": false,
  "dead": false,
  "addresses": [{
    "address1": "Hauptstr. 12",
    "cityVillage": "München",
    "stateProvince": "Bayern",
    "country": "Germany",
    "postalCode": "80331",
    "preferred": true
  }],
  "attributes": [{
    "attributeType": "14d4f066-15f5-102d-96e4-000c29c2a5d7",
    "value": "+49123456789"
  }]
}

### 12.  Обновление gender, birthdate, dead=true + deathDate -> 200
POST http://localhost/openmrs/ws/rest/v1/person/1da80315-96ec-47de-aa32-61a864002b1f
Content-Type: application/json
Authorization: Basic YWRtaW46QWRtaW4xMjM=
Accept: application/json

{
  "names": [{"givenName": "Ivan", "middleName": "Petrovich", "familyName": "Ivanov", "preferred": true}],
  "gender": "M",
  "birthdate": "2000-01-01",
  "birthdateEstimated": false,
  "dead": true,
    "deathDate": "2023-12-31",
    "causeOfDeathNonCoded": "Unknown cause",
  "addresses": [{
    "address1": "Hauptstr. 12",
    "cityVillage": "München",
    "stateProvince": "Bayern",
    "country": "Germany",
    "postalCode": "80331",
    "preferred": true
  }],
  "attributes": [{
    "attributeType": "14d4f066-15f5-102d-96e4-000c29c2a5d7",
    "value": "+49123456789"
  }]
}

### 13.  Удаление полное, из БД (если на основе person создан пациент, нельзя удалить) -> 204
DELETE http://localhost/openmrs/ws/rest/v1/person/00511e00-f662-4cfd-b2e1-3a50d70703c6?purge=true
Content-Type: application/json
Authorization: Basic YWRtaW46QWRtaW4xMjM=
Accept: application/json

### 14.  Удаление частичное (пометка об удалении, но из БД не удаляется) -> 204
DELETE http://localhost/openmrs/ws/rest/v1/person/fc35454b-2945-4d5d-85d1-75ecc0e79ae1
Content-Type: application/json
Authorization: Basic YWRtaW46QWRtaW4xMjM=
Accept: application/json

### 15.  Добавление дополнительного имени (non-preferred) -> 201
POST http://localhost/openmrs/ws/rest/v1/person/1da80315-96ec-47de-aa32-61a864002b1f/name
Content-Type: application/json
Authorization: Basic YWRtaW46QWRtaW4xMjM=
Accept: application/json

{
  "givenName": "Ваня",
  "middleName": null,
  "familyName": "Иванов",
  "preferred": false
}

### 16.  Добавление адреса (address1, cityVillage, country и т.д.) -> 201
POST http://localhost/openmrs/ws/rest/v1/person/1da80315-96ec-47de-aa32-61a864002b1f/address
Content-Type: application/json
Authorization: Basic YWRtaW46QWRtaW4xMjM=
Accept: application/json

{
  "address1": "Lenina 45, кв. 12",
  "address2": "подъезд 3",
  "cityVillage": "Москва",
  "stateProvince": "Москва",
  "country": "Россия",
  "postalCode": "125009",
  "latitude": "55.7558",
  "longitude": "37.6173",
  "preferred": true
}

### 17.  Добавление кастомного атрибута (например, "Email") -> 201
POST http://localhost/openmrs/ws/rest/v1/person/1da80315-96ec-47de-aa32-61a864002b1f/attribute
Content-Type: application/json
Authorization: Basic YWRtaW46QWRtaW4xMjM=
Accept: application/json

{
  "attributeType": {
    "uuid": "c90843ac-f8dd-11f0-8d24-0242ac150002"
  },
  "value": "ivan.ivanov@example.com"
}

### 18. Список всех атрибутов Person -> 200
GET http://localhost/openmrs/ws/rest/v1/person/1da80315-96ec-47de-aa32-61a864002b1f/attribute
Content-Type: application/json
Authorization: Basic YWRtaW46QWRtaW4xMjM=
Accept: application/json