name: OpenMRS deployment

on:
  # На любой push (коммит) в любой ветку
  push:
    branches:
      - '**'  # Все ветки
    paths-ignore:
      - '**.md'  # Не запускать на изменения в документации
      - '.gitignore'

  # На pull request
  pull_request:
    branches:
      - main

jobs:

  # Поднимается OpenMRS
  app:
    uses: ./.github/workflows/app-stage.yml

  # Прогоняются API тесты
  automation-api:
    needs: [ db, backend, frontend, gateway ]
    uses: ./.github/workflows/automation.yml
    with:
      package: api

  # Прогоняются UI тесты
  automation-ui:
    needs: [ db, backend, frontend, gateway ]
    uses: ./.github/workflows/automation.yml
    with:
      package: ui

  cleanup:
    needs: [ app, automation-api, automation-ui ]
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Stop and remove all containers from this run
        run: |
          docker stop $(docker ps -q) || true
          docker rm -f $(docker ps -aq) || true
          
          docker volume rm $(docker volume ls -q) || true
          
          docker system prune -f --volumes || true

